services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=teneastdb
    ports:
      - "5432:5432"

  backend:
    build: ./teneastbackend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./teneastclient
    container_name: frontend
    ports:
      - 3000:3000